project_id = "kpirgtjvbojofqqjhewg"

[functions.send-invitation]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.update-user-role]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.create-super-admin]
verify_jwt = false
